name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-makefile-targets:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Start Kafka and ZooKeeper
        run: make up

      - name: Wait for services to initialize
        run: |
          echo "Waiting for containers to start..."
          sleep 10
          docker ps

      - name: Wait for ZooKeeper to be ready
        run: |
          echo "Waiting for ZooKeeper to be ready..."
          for i in {1..30}; do
            # Use netcat to check if ZooKeeper port is accessible instead of 'ruok' command
            if docker exec zookeeper sh -c 'nc -z localhost 2181' >/dev/null 2>&1; then
              echo "ZooKeeper is ready!"
              break
            fi
            echo "Waiting for ZooKeeper... (attempt $i/30)"
            sleep 2
          done

      - name: Wait for Kafka to be ready
        run: |
          echo "Waiting for Kafka to be ready..."
          for i in {1..60}; do
            if docker exec kafka kafka-topics --list --bootstrap-server localhost:9092 >/dev/null 2>&1; then
              echo "Kafka is ready!"
              break
            fi
            echo "Waiting... (attempt $i/60)"
            sleep 3
          done
          # Verify Kafka is actually ready
          echo "Final verification:"
          docker exec kafka kafka-topics --list --bootstrap-server localhost:9092

      - name: Create topic
        run: |
          echo "Creating topic..."
          make create-topic
          echo "Verifying topic was created:"
          docker exec kafka kafka-topics --list --bootstrap-server localhost:9092

      - name: Install Python dependencies
        run: make install

      - name: Verify Python dependencies
        run: pip list | grep confluent-kafka

      - name: Run producer (should complete in one execution)
        run: |
          echo "Running producer..."
          make producer
          echo "Producer completed successfully!"

      - name: Run consumer (should auto-terminate after receiving messages or 10s timeout)
        run: |
          echo "Running consumer..."
          make consumer
          echo "Consumer completed successfully!"

      - name: Stop Kafka and ZooKeeper
        run: make down
        if: always()

      - name: Verify all targets completed successfully
        run: echo "All Makefile PHONY targets executed successfully!"

