name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This is a placeholder for future CI steps."
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This is a placeholder for future CI steps."

